### ISSUE TITLE
noMultiproc과 comfortable merge하겠습니다

### ISSUE THREAD

**Issue by Ihm-hyun-sir** [20-2-SKKU-OSS/2020-2-OSS-6-Project#16]
noMultiproc 기능 : 크롤링을 하는 도중 엑셀파일에서 그 내용 보기 가능
comfortable 기능 : 크롤링 시작 시 사용자에게 시간대 / 카테고리 입력받아서 크롤링

예상 기능 : 사용자가 입력한 시간대의 카테고리 기사를 크롤링하는 것을 엑셀파일에서 실시간으로 확인 가능

merge 방식 : 몇줄 안되기도 하고, 같은 파일을 고쳤기에 수동으로 noMultiproc 브랜치에 merge하겠습니다

**Comment by hj10271803** [comment]
작동 확인했습니다.
