### ISSUE TITLE
실행이 완료 될 때까지 크롤링 결과 확인 불가

### ISSUE THREAD

**Issue by Changooo** [20-2-SKKU-OSS/2020-2-OSS-6-Project#5]
### **csv파일 중도 확인 불가**

실행시간이 유의미하게 길 때, 실행하는 동안 csv파일을 통해 크롤링 결과를 확인 할 수 없습니다.

> 1년 정도 긴 분량의 기사를 크롤링한다면, 실행 후 10시간 이상을 기다려야 크롤링 결과를 확인 할 수 있는 것으로 확인됩니다.

해당 이슈는 멀티프로세싱을 사용하고 있어 생기는 현상으로 보이며, 멀티프로세싱을 사용하는 옵션과 사용하지 않는 옵션 둘 다 제공되면 더 좋을 것 같습니다.

- [ ] start 메소드에 멀티프로세싱 옵션 추가

**Comment by Ihm-hyun-sir** [comment]
noMultiProc 브랜치로 해결된 것 확인 했습니다
